### ISSUE TITLE
Have a look

### ISSUE THREAD

**Issue by melMass** [fredrikaverpil/pyvfx-boilerplate#16]
Hi,

I've made a cookiecutter version, check it out:
[cookiecutter-pyvfx-boilerplate](https://github.com/melMass/cookiecutter-pyvfx-boilerplate)

This is really a copy paste of yours with minor updates and cookiecutterized.
I'll try to ehance it further but the workflow to code cookiecutters is not ideal, at least I haven't found an efficient workflow yet.

Thanks for the base.

**Comment by fredrikaverpil** [comment]
Cool, cheers.
